CREATE DATABASE ALMACEN;
USE ALMACEN;
CREATE TABLE PRODUCTO(CODIGO TINYINT UNSIGNED PRIMARY KEY,
	DESCRIPCION VARCHAR(200) UNIQUE NOT NULL,
	STOCK SMALLINT UNSIGNED DEFAULT 10,
	CATEGORIA SET ('Textil', 'Juguetes', 'Hogar'),
	precio decimal (8,2),
	check (precio>0)
);
-- Primer insert correcto
INSERT INTO PRODUCTO (CODIGO, DESCRIPCION, STOCK, CATEGORIA, PRECIO)
VALUES (1, 'Camiseta blanca', 20, 'Textil', 15.99);

-- Segundo insert con el mismo CODIGO → ERROR de clave primaria duplicada
INSERT INTO PRODUCTO (CODIGO, DESCRIPCION, STOCK, CATEGORIA, PRECIO)
VALUES (1, 'Pantalón vaquero', 15, 'Textil', 29.99);

-- Insert correcto
INSERT INTO PRODUCTO (CODIGO, DESCRIPCION, STOCK, CATEGORIA, PRECIO)
VALUES (2, 'Toalla de baño', 30, 'Hogar', 12.50);

-- Descripción repetida → ERROR UNIQUE
INSERT INTO PRODUCTO (CODIGO, DESCRIPCION, STOCK, CATEGORIA, PRECIO)
VALUES (3, 'Toalla de baño', 25, 'Hogar', 14.00);

-- DESCRIPCION no puede ser NULL → ERROR NOT NULL
INSERT INTO PRODUCTO (CODIGO, DESCRIPCION, STOCK, CATEGORIA, PRECIO)
VALUES (4, NULL, 10, 'Juguetes', 8.99);

-- Precio 0 → ERROR CHECK
INSERT INTO PRODUCTO (CODIGO, DESCRIPCION, STOCK, CATEGORIA, PRECIO)
VALUES (5, 'Pelota de goma', 50, 'Juguetes', 0);

-- CATEGORIA no existe en el conjunto → ERROR DE VALOR SET
INSERT INTO PRODUCTO (CODIGO, DESCRIPCION, STOCK, CATEGORIA, PRECIO)
VALUES (6, 'Lámpara LED', 12, 'Electrónica', 22.90);

-- CODIGO negativo → ERROR fuera de rango
INSERT INTO PRODUCTO (CODIGO, DESCRIPCION, STOCK, CATEGORIA, PRECIO)
VALUES (-1, 'Silla de madera', 5, 'Hogar', 45.00);
